### ISSUE TITLE
See more text not returned in search

### ISSUE THREAD

**Issue by arothmel** [veteransaffairscanada/vac-benefits-directory#1657] opened 2019-01-04 17:48 UTC

**Comment by arothmel** [comment] 2019-01-04 17:55
Because the See more text is hidden by default the See more words are not picked up by search.  A user searching for hearing aid is no better off than before. 
Even after See more has been selected and the card is expanded, the card closes on Search and the See more text is not found. Could all of the displayed cards be opened for search?
To duplicate: Open Disability Award and search for the displayed word 'hearing aid' as an example.

**Comment by brdunfield** [comment] 2019-01-07 14:39
Possibly duplicate of #1301

**Comment by smcmurtry** [comment] 2019-01-11 18:56
To fix this we will need to include the see more text in the search index.

**Comment by smcmurtry** [comment] 2019-01-11 18:57
![](https://github.trello.services/images/mini-trello-icon.png) [Make the search work for "see more" example content](https://trello.com/c/DW9nCCwM/147-make-the-search-work-for-see-more-example-content)

**Comment by smcmurtry** [comment] 2019-01-11 18:57
![](https://github.trello.services/images/mini-trello-icon.png) [Make the search work for "see more" example content](https://trello.com/c/DW9nCCwM/147-make-the-search-work-for-see-more-example-content)

**Closed as completed** 2019-01-16 16:49 UTC
