### ISSUE TITLE
Next steps styling to match new designs

### ISSUE THREAD

**Issue by brdunfield** [veteransaffairscanada/vac-benefits-directory#1863] opened 2019-02-19 20:20 UTC
See: https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5c0a5ea447d3cdb754479984

**Comment by SupeDeDupe** [comment] 2019-05-10 12:55
#2051 is a duplicate of this issue.

**Closed as completed by SupeDeDupe** 2019-05-10 12:55 UTC
